#!/usr/bin/env python3
"""Generate lib/src/centroids.g.dart — a 6-digit subdistrict geocode -> [lat, lng]
reference-point table for nearest-point reverse geocoding.

Sources (read-only, NOT shipped with the package):
  * DOPA subdistrict coordinate dataset (กรมการปกครอง), the authoritative points:
      ../go-thaiaddress/reference/dopa-tambon.xlsx  (AD_LEVEL==4: TA_ID, LAT, LONG)
    Government factual data; credit DOPA when redistributing.
  * kongvut/thai-province-data (MIT), lat/long fallback:
      ../_thaiaddr_raw/sub_district.json
  * The authoritative code set is thai_provinces' own 7452 subdistrict codes,
    dumped to tool/subdistrict_codes.json (so corrected codes — e.g. the
    เวียงเก่า/ขอนแก่น district fix — match what the package actually serves).

For each code: prefer the DOPA point (averaged when a TA_ID has several rows),
then the kongvut lat/long, then the mean of sibling subdistricts in the same
district; coordinates are quantized to 4 decimal places (~11 m).

Run from the package root:  python3 tool/gen_centroids.py
"""
import json
import os
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DOPA = os.path.join(ROOT, "..", "go-thaiaddress", "reference", "dopa-tambon.xlsx")
JSON = os.path.join(ROOT, "..", "_thaiaddr_raw", "sub_district.json")
CODES = os.path.join(HERE, "subdistrict_codes.json")
OUT = os.path.join(ROOT, "lib", "src", "centroids.g.dart")


def q(x):
    return round(float(x), 4)


def load_dopa():
    import openpyxl

    wb = openpyxl.load_workbook(DOPA, read_only=True, data_only=True)
    ws = wb.active
    it = ws.iter_rows(values_only=True)
    h = list(next(it))
    idx = {str(x): i for i, x in enumerate(h)}
    adl, ta, la, lo = idx["AD_LEVEL"], idx["TA_ID"], idx["LAT"], idx["LONG"]
    acc = defaultdict(list)
    for r in it:
        if str(r[adl]) != "4" or r[ta] is None or r[la] in (None, "") or r[lo] in (None, ""):
            continue
        acc[int(r[ta])].append((float(r[la]), float(r[lo])))
    return {c: (sum(p[0] for p in v) / len(v), sum(p[1] for p in v) / len(v)) for c, v in acc.items()}


def load_json():
    rows = json.load(open(JSON, encoding="utf-8"))
    out = {}
    for r in rows:
        if r.get("lat") not in (None, "") and r.get("long") not in (None, ""):
            out[int(r["id"])] = (float(r["lat"]), float(r["long"]))
    return out


def main():
    dopa, kong = load_dopa(), load_json()
    codes = json.load(open(CODES, encoding="utf-8"))  # [{code, districtCode}]
    by_district = defaultdict(list)

    # First pass: direct coordinate (DOPA preferred, else kongvut).
    coord = {}
    src = defaultdict(int)
    for row in codes:
        c, dc = int(row["code"]), int(row["districtCode"])
        if c in dopa:
            coord[c] = dopa[c]; src["dopa"] += 1
        elif c in kong:
            coord[c] = kong[c]; src["kongvut"] += 1
        if c in coord:
            by_district[dc].append(coord[c])

    # Second pass: fill the rest from the district mean.
    out = dict(coord)
    for row in codes:
        c, dc = int(row["code"]), int(row["districtCode"])
        if c in out:
            continue
        sib = by_district.get(dc)
        if sib:
            out[c] = (sum(p[0] for p in sib) / len(sib), sum(p[1] for p in sib) / len(sib))
            src["district-mean"] += 1
        else:
            src["skipped"] += 1

    lines = ["  {}: [{}, {}],".format(c, q(out[c][0]), q(out[c][1])) for c in sorted(out)]
    body = (
        "// GENERATED by tool/gen_centroids.py — do not edit by hand.\n"
        "//\n"
        "// 6-digit DOPA subdistrict (tambon) geocode -> representative reference\n"
        "// point [latitude, longitude] (decimal degrees, WGS84, ~11 m precision).\n"
        "// Source: DOPA (กรมการปกครอง) subdistrict coordinate dataset (government\n"
        "// factual data), gaps filled from kongvut/thai-province-data (MIT).\n"
        "\n"
        "/// Subdistrict reference points: 6-digit code -> `[lat, lng]`.\n"
        "const Map<int, List<double>> kSubdistrictCentroids = <int, List<double>>{\n"
        + "\n".join(lines)
        + "\n};\n"
    )
    open(OUT, "w", encoding="utf-8").write(body)
    print("wrote", len(out), "of", len(codes), "codes ->", OUT)
    print("sources:", dict(src))


if __name__ == "__main__":
    main()
